### ISSUE TITLE
Provide a way to easily close options panel

### ISSUE THREAD

**Issue by georapbox** [tomayac/SVGcode#37] opened 2021-11-25 13:54 UTC
## Description

In mobile views, when the options panel is open and options are expanded, it's a bit difficult for the user to close the panel. The panel can be closed if the user clicks outside, but It in order to achieve this they need to collapse one or more options, so that the panel's height becomes smaller and the clickable area increases.

Please see attached screenshot. Red rectangles represent the clickable areas.

![Screenshot 2021-11-25 at 3 46 06 PM](https://user-images.githubusercontent.com/6596039/143453228-056ecc84-c2aa-4c72-8b96-9b34b71b8faf.png)

**Comment by georapbox** [comment] 2021-11-25 13:56
Would you mind if I created a PR for this one with a solution similar to the provided screenshot below?

![prototype](https://user-images.githubusercontent.com/6596039/143454163-35e65ae5-50ab-473a-9817-0ec516745ccd.png)

**Comment by tomayac** [comment] 2021-11-25 14:44
Oh, this looks like a regression since I changed the sidebar width (https://github.com/tomayac/SVGcode/blob/31eb06e834cfacafb8d18863a93f4ba5cf756ff1/src/css/style.css#L354) (it was a hard-coded `width` before). Now the "Reset All" button consumes the entire space. 

The actual idea was to make the summary occupy the entire space that is _not_ the sidebar when it's open, so the user can click anywhere (they actually click the `summary`, but don't realize it) to close the sidebar. 

I'm not opposed to adding an explicit "Close" button, so the user can either click "anywhere" or use the button. 

I'd be happy to merge a PR that tackles this. Thanks in advance!

**Comment by georapbox** [comment] 2021-11-25 15:16
You're right, the `summary` is indeed occupying the whole space, although invisible. And from technical perspective, it works fine. The actual "problem" is that when the `details` inside the sidebar are expanded, they take up the whole space and the remaining `summary` clickable area is very small. Therefore, as a user I have to collapse one or two `details` elements so that I can click the summary and the sidebar to close. That's why I came up with the idea of having a close button that is straightforward and the user cannot miss.

I will prepare a PR and we can discuss further.

Thanks!

**Comment by tomayac** [comment] 2021-11-26 08:10
Fixed via https://github.com/tomayac/SVGcode/pull/38.

**Closed by tomayac** 2021-11-26 08:10 UTC
